image: noasakurajin/libtrainsim-build-container:fedora

build:
  stage: build
  script:
    - meson setup build
    - meson compile -C build
    - meson test -C build
  only:
    - merge_requests
    - main
