image: gcc:latest

build:
  stage: build
  script:
    - echo 'echo $K8S_SECRET_GITLAB_TOKEN' > $HOME/.git-askpass && chmod +x $HOME/.git-askpass
    - export GIT_ASKPASS=$HOME/.git-askpass
    - git config --global url."https://api@git.thm.de/".insteadOf "https://git.thm.de/"
    - git config --global url."https://ssh@git.thm.de/".insteadOf "ssh://git@git.thm.de/"
    - git config --global url."https://git@git.thm.de/".insteadOf "git@git.thm.de:"
    - apt-get update
    - apt-get install --yes gfortran-8
    - update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 1
    - apt-get install --yes python3-pip libopencv-dev libsdl2-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavresample-dev libavutil-dev libswresample-dev libswscale-dev libpostproc-dev
    - python3 -m pip install meson ninja
    - python3 -m pip install glad
    - meson setup build
    - meson compile -C build
    - meson test -C build
