name: libtrainsim # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.11.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: The reference implementaion of libtrainsim # 79 char long summary
description: |
  This package contains builds of the reference implementation of libtrainsim.
  You can specify the configuration of the simulator by passing a simulator configuration as a command line parameter.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
#  - build-on: s390x
#  - build-on: ppc64el
#  - build-on: armhf
  - build-on: arm64
  - build-on: amd64

compression: lzo

parts:
  libtrainsim:
    # See 'snapcraft plugins'
    plugin: dump
    source-type: git
    source: https://git.thm.de/bahn-simulator/simulator.git
    #source: .
    override-build: |
        export PATH=$PATH:/root/.local/bin
        export MARCH="native"

        if [ "$SNAPCRAFT_TARGET_ARCH" == "amd64" ];
        then
            export MARCH="athlon-fx"
        fi

        if [ "$SNAPCRAFT_TARGET_ARCH" == "arm64" ];
        then
            export MARCH="armv8-a"
        fi

        python3 -m pip install "meson>=0.57.0"
        meson setup --prefix=/snap/libtrainsim/current/usr -Dno-data=true -Db_lto=true -Db_pgo=off -Dmarch="$MARCH" --optimization 2 build
        meson configure build
        meson compile -C build
        meson install -C build
        cp de.thm.simulator.desktop /snap/libtrainsim/current/usr/share/libtrainsim/
    
    organize: 
      /snap/libtrainsim/current/usr: usr
      
    build-packages:
        - python3
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - g++
        - ninja-build

        - libsdl2-dev
        - libsdl2-image-dev
        - libsdl2-gfx-dev
        - libavcodec-dev
        - libavdevice-dev
        - libavfilter-dev
        - libavformat-dev
        - libavresample-dev 
        - libavutil-dev
        - libswresample-dev 
        - libswscale-dev 
        - libpostproc-dev  

    stage-packages:
        - libsdl2-2.0-0
        - libsdl2-image-2.0-0
        - libsdl2-gfx-1.0-0
        - libxss1
        - libaom0
        - libavcodec58
        - libavformat58
        - libavutil56
        - libbluray2
        - libchromaprint1
        - libcodec2-0.9
        - libgme0
        - libgsm1
        - libmp3lame0
        - libmpg123-0
        - libnuma1
        - libopenmpt0
        - libopus0
        - libshine3
        - libsnappy1v5
        - libsoxr0
        - libspeex1
        - libssh-gcrypt-4
        - libswresample3
        - libswscale5
        - libtheora0
        - libtwolame0
        - libva-drm2
        - libva-x11-2
        - libva2
        - libvdpau1
        - libvpx6
        - libwavpack1
        - libwebpmux3
        - libx264-155
        - libx265-179
        - libxvidcore4
        - libzvbi0
        - ocl-icd-libopencl1

apps:
  libtrainsim:
    extensions: [gnome-3-38]
    desktop: usr/share/libtrainsim/de.thm.simulator.desktop
    plugs:
        - home
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - gtk-3-themes
        - icon-themes
        - gnome-3-38-2004
        - audio-playback
        - serial-port
    command: usr/share/libtrainsim/simulator

plugs:
  libtrainsim-data-plug:
    interface: content
    content: data
    target: $SNAP/data
