name: libtrainsim # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.5.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: The reference implementaion of libtrainsim # 79 char long summary
description: |
  This package contains builds of the reference implementation of libtrainsim with the date for one track.
  At the moment this track is hardcoded but there will be many updates in the future.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
#  - build-on: s390x
#  - build-on: ppc64el
#  - build-on: armhf
  - build-on: arm64
  - build-on: amd64

compression: lzo

parts:
  libtrainsim:
    # See 'snapcraft plugins'
    plugin: dump
    source-type: git
    source: https://git.thm.de/bahn-simulator/simulator.git
    override-build: |
        python3 -m pip install --upgrade pip setuptools wheel
        export PATH=$PATH:/root/.local/bin
        python3 -m pip install "meson>=0.57.0"
        CC=clang-10 CXX=clang++-10 meson setup --prefix $SNAPCRAFT_PART_INSTALL/usr/local -Dno-data=true --optimization 2 build
        meson compile -C build
        meson install -C build
        rsync --links --remove-source-files -r $SNAPCRAFT_PART_INSTALL/usr/local/lib/ $SNAPCRAFT_PART_INSTALL/usr/lib
        rsync --links --remove-source-files -r $SNAPCRAFT_PART_INSTALL/usr/local/include/ $SNAPCRAFT_PART_INSTALL/usr/include
        cp de.thm.simulator.desktop $SNAPCRAFT_PART_INSTALL/usr/local/share/libtrainsim/
        
    override-stage: |
        snapcraftctl stage
        sed -i 's|$SNAPCRAFT_STAGE/usr|/snap/libtrainsim/current/usr|g' $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig/*.pc
        cat $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig/trainsim-core.pc
        
    build-packages:
        - python3
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - g++
        - git
        - ninja-build
        - curl
        - bash
        - rsync
        - wget
        - lsb-release
        - software-properties-common
        - lld-10
        - lldb-10
        - clang-10

        - libsdl2-dev
        - libavcodec-dev
        - libavdevice-dev
        - libavfilter-dev
        - libavformat-dev
        - libavresample-dev 
        - libavutil-dev
        - libswresample-dev 
        - libswscale-dev 
        - libpostproc-dev
        
    stage-packages:
        - libsdl2-2.0-0
        - libxss1
        - libaom0
        - libavcodec58
        - libavformat58
        - libavutil56
        - libbluray2
        - libchromaprint1
        - libcodec2-0.9
        - libgme0
        - libgsm1
        - libmp3lame0
        - libmpg123-0
        - libnuma1
        - libopenmpt0
        - libopus0
        - libshine3
        - libsnappy1v5
        - libsoxr0
        - libspeex1
        - libssh-gcrypt-4
        - libswresample3
        - libswscale5
        - libtheora0
        - libtwolame0
        - libva-drm2
        - libva-x11-2
        - libva2
        - libvdpau1
        - libvpx6
        - libwavpack1
        - libwebpmux3
        - libx264-155
        - libx265-179
        - libxvidcore4
        - libzvbi0
        - ocl-icd-libopencl1
    
apps:
  libtrainsim:
    extensions: [gnome-3-38]
    desktop: usr/local/share/libtrainsim/de.thm.simulator.desktop
    plugs:
        - home
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
    command: usr/local/share/libtrainsim/simulator
    
plugs:
  libtrainsim-data-plug:
    interface: content
    content: data
    target: $SNAP/data
    
